---
config:
  look: neo
---
classDiagram
    namespace PresentationLayer {
        class API {
            <<Interface>>
            +UserAPI
            +PlaceAPI
            +ReviewAPI
            +AmenityAPI

            +Create()
            +Read()
            +Update()
            +Delete()
        }
    
    }
    
    
    namespace BusinessLogicLayer {
        class Facade {
            <<Facade Pattern>>
            +createUser()
            +createPlace()
            +createReview()
            +manageAmenities()
        }
        
        class Models {
            +User
            +Place
            +Review
            +Amenity

            +Create()
            +Read()
            +Update()
            +Delete()
        }
    }
    
    namespace PersistenceLayer {
        class Repository {
            +UserRepository
            +PlaceRepository
            +ReviewRepository
            +AmenityRepository

            +Create()
            +Read()
            +Update()
            +Delete()
        }
    }
    
    API --> Facade : Uses Facade Pattern
    Facade --> Models : Manages Business Logic
    Models --> Repository : Data Persistence