classDiagram

    namespace PresentationLayer{
        class APIsREST
        class route_endpoints
        class requêtes_HTTP

    }

    namespace BusinessLogicLayer{
        class model(User,Place,Review,Amenity)
        class jobs_rules
        class complex_validation
    }
    
    namespace PersitenceLayers{
        class repositories
        class BDD_acces
        class requet SQL 
          
    }
